source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MTPhotoPicker_Example', :exclusive => true do
  pod "MTPhotoPicker", :path => "../"
end

target 'MTPhotoPicker_Tests', :exclusive => true do
  pod "MTPhotoPicker", :path => "../"

  
end
